features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
enable_customize: '0'
logo_width: ''
logo_padding_top: ''
logo_padding_bottom: ''
sticky_menu: '0'
site_layout: wide
preloader: '0'
google_key: AIzaSyDklPuT2SCmcmlflaoZ4B0WywYK_em79x4
default_header: header
header_info: ''
customize_css: ''
