features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://pwm-logo-blue-med.png'
favicon:
  use_default: 1
enable_customize: '1'
logo_width: ''
logo_padding_top: ''
logo_padding_bottom: ''
listing_search_action: listings
listing_search_actionen: listings
listing_search_actionfr: listings
listing_search_actionde: listings
sticky_menu: '0'
site_layout: wide
preloader: '0'
google_key: ''
default_header: header
header_info: ''
customize_css: ''
